// <auto-generated />
using System;
using Biuro_Podrozy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biuro_Podrozy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220126183850_Migracja2")]
    partial class Migracja2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BiuroItemDepartureCity", b =>
                {
                    b.Property<int>("BiuroItemsId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureCitiesDepartureCityId")
                        .HasColumnType("int");

                    b.HasKey("BiuroItemsId", "DepartureCitiesDepartureCityId");

                    b.HasIndex("DepartureCitiesDepartureCityId");

                    b.ToTable("BiuroItemDepartureCity");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.BiuroItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PhotosPhotoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TravelPlace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhotosPhotoId");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BiuroItemId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("Seats")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BookId");

                    b.HasIndex("BiuroItemId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.DepartureCity", b =>
                {
                    b.Property<int>("DepartureCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartureCityId");

                    b.ToTable("Dc");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.ToTable("Ph");
                });

            modelBuilder.Entity("BiuroItemDepartureCity", b =>
                {
                    b.HasOne("Biuro_Podrozy.Models.BiuroItem", null)
                        .WithMany()
                        .HasForeignKey("BiuroItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biuro_Podrozy.Models.DepartureCity", null)
                        .WithMany()
                        .HasForeignKey("DepartureCitiesDepartureCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.BiuroItem", b =>
                {
                    b.HasOne("Biuro_Podrozy.Models.Photo", "Photos")
                        .WithMany("BiuroItems")
                        .HasForeignKey("PhotosPhotoId");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.Book", b =>
                {
                    b.HasOne("Biuro_Podrozy.Models.BiuroItem", "BiuroItem")
                        .WithMany("Books")
                        .HasForeignKey("BiuroItemId");

                    b.Navigation("BiuroItem");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.BiuroItem", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Biuro_Podrozy.Models.Photo", b =>
                {
                    b.Navigation("BiuroItems");
                });
#pragma warning restore 612, 618
        }
    }
}
